import type { CustomRules } from './converters/types';
export declare const description = "\n\"\"\"\nThis file was generated by graphql-schema-generator which is\nmaintained by prisma-korea.\n\nDo not make changes to this file directly.\nRead more about in https://github.com/prisma-korea/graphql-schema-generator.\n\"\"\"\n";
export declare type Config = {
    customRules?: CustomRules;
    [key: string]: any;
};
declare const generateGraphqlSchema: (source: string, config: Config) => Promise<string>;
export default generateGraphqlSchema;
//# sourceMappingURL=generateGraphqlSchema.d.ts.map