"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.description = void 0;
const tslib_1 = require("tslib");
const parse_1 = (0, tslib_1.__importDefault)(require("./parse"));
const transpile_1 = (0, tslib_1.__importDefault)(require("./transpile"));
exports.description = `
"""
This file was generated by graphql-schema-generator which is
maintained by prisma-korea.

Do not make changes to this file directly.
Read more about in https://github.com/prisma-korea/graphql-schema-generator.
"""
`;
const generateGraphqlSchema = async (source, config) => {
    const model = await (0, parse_1.default)(source);
    const { createCRUD, ...rest } = config;
    const graphqlSchema = createCRUD === 'true'
        ? (0, transpile_1.default)(model, {
            ...rest,
            createQuery: 'true',
            createMutation: 'true',
        })
        : (0, transpile_1.default)(model, {
            ...rest,
            createQuery: 'false',
            createMutation: 'false',
        });
    return exports.description + graphqlSchema;
};
exports.default = generateGraphqlSchema;
//# sourceMappingURL=generateGraphqlSchema.js.map